// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJH0mBRQ6O2TWXBOydG_m4jpPSZTu0HnE',
    appId: '1:1049747017042:web:0214826a66658b9897fe8b',
    messagingSenderId: '1049747017042',
    projectId: 'ai-life-coach-5c113',
    authDomain: 'ai-life-coach-5c113.firebaseapp.com',
    storageBucket: 'ai-life-coach-5c113.firebasestorage.app',
    measurementId: 'G-LS745PF16M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGQT5CKGNxaSKsGvfo-a0TdfIpTazfaPc',
    appId: '1:1049747017042:android:e449a60231dd38df97fe8b',
    messagingSenderId: '1049747017042',
    projectId: 'ai-life-coach-5c113',
    storageBucket: 'ai-life-coach-5c113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz7drOFqCi0Sg8Pk7nUEAX3yA0CsJfjJI',
    appId: '1:1049747017042:ios:58473677a565964b97fe8b',
    messagingSenderId: '1049747017042',
    projectId: 'ai-life-coach-5c113',
    storageBucket: 'ai-life-coach-5c113.firebasestorage.app',
    iosClientId: '1049747017042-8fc2s4mkprote3v15n0h83e4lfhfhv8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiLifeCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz7drOFqCi0Sg8Pk7nUEAX3yA0CsJfjJI',
    appId: '1:1049747017042:ios:58473677a565964b97fe8b',
    messagingSenderId: '1049747017042',
    projectId: 'ai-life-coach-5c113',
    storageBucket: 'ai-life-coach-5c113.firebasestorage.app',
    iosClientId: '1049747017042-8fc2s4mkprote3v15n0h83e4lfhfhv8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiLifeCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJH0mBRQ6O2TWXBOydG_m4jpPSZTu0HnE',
    appId: '1:1049747017042:web:eaaed6deae41560297fe8b',
    messagingSenderId: '1049747017042',
    projectId: 'ai-life-coach-5c113',
    authDomain: 'ai-life-coach-5c113.firebaseapp.com',
    storageBucket: 'ai-life-coach-5c113.firebasestorage.app',
    measurementId: 'G-D7BDWKQB6L',
  );
}
